### ISSUE TITLE
Feature request: incorporate novel exons into mergeNovelSplice pipeline

### ISSUE THREAD

**Issue by warrenmcg** [hartleys/QoRTs#11]
Hi Steve,

I'm reviewing JunctionSeq output on my data after merging novel splices, and I'm noticing more than a few cases where novel junctions that are significantly different between conditions flank an exon that is missing from the annotation. Ideally then, one would want to annotate that novel exon to include into the calculations. However, this sounds like a very difficult thing to accomplish (cassette exons seem easy enough, but 5'/3' alternative splice sites and junctions that extend beyond the edge of the current gene model do not), so I'll simply ask if it's already on the to-do list.

Thanks,
Warren

**Comment by hartleys** [comment]
I've actually thought about this a lot. Unfortunately, the problem is much
trickier than it sounds.

Cassette exons are easy to recognize by eye, but can be really tricky to
identify automatically. There are a lot of edge cases that you would have
to set. For example: what if there's a novel internal promoter? Sometimes
it can be hard to tell the difference between a novel promoter and a novel
alternative donor site. You can heuristically guess based on the distance,
but sometimes there are large exons or small introns, so your guess might
be wrong. Furthermore, different organisms have very different intron/exon
structures, so any solution I come up with that works great on human data
will often work terribly on, say, Toxoplasma Gondii. I would of course
include settable parameters to alter the heuristic, but there would have to
be a bunch of them and they would probably be quite confusing.

What you really want is a separate "novel exon discovery" tool, which would
work kind of like our existing assemblers (trinity, cufflinks, etc), except
that it only tries to solve the (much simpler) problem of identifying
discrete exons. It would take the read coverage across these purported
exonic regions and detect novel exons (and intron retentions too, probably).

I've never seen a tool with such a capability, at least not one that looked
effective/usable enough to be worth the trouble. You can try cufflinks, but
in my experience it's often not worth the trouble.

This isn't really on my current to-do list. It's more of a "what should I
do after JunctionSeq is done" sort of idea.

-Steve

**Comment by warrenmcg** [comment]
I see. One tool that I'm aware of that attempts to do this is SplAdder, which was published just a few weeks ago: [github repository](https://github.com/ratschlab/spladder), [Bioinformatics article](http://bioinformatics.oxfordjournals.org/content/early/2016/02/11/bioinformatics.btw076).
