### ISSUE TITLE
Original BAM name from QoRTs output

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#25]
Hi,
Is name of BAM file used during a QoRTs run saved anywhere in the output results/directory?
Thanks.

**Comment by hartleys** [comment]
There should be a log file named "QC.<randomString>.log". The random string of characters is there to prevent multiple successive QoRTs runs from overwriting one another's logs).

This should start with a listing of all the input variables, including the input files.

**Comment by royfrancis** [comment]
I am not sure if you know of multiqc (https://github.com/ewels/MultiQC). It creates interactive plots and reports from the output of various bio-info tools. I was considering asking the author to add a module for qorts. The first step is to identify the sample name. One could obviously use the directory name for each sample but the user is free to set that to whatever. It would be easy if the BAM file name could be obtained from a consistent location. Any plans of including the file name in any of the standard files? the summary file for example?

**Comment by hartleys** [comment]
Why would it need to identify the sample name from the QC file?

Identifying the sample ID depends on your pipeline. In the pipelines where I have worked, for example, each biological sample may be run across multiple HiSeq lanes (due to library multiplexing, to reduce technical bias). Thus, identifying sample ID's from the filename isn't necessarily possible.

QoRTs also allows you to read bam files from Standard input (ie, a stream), in which case QoRTs never has access to the actual filename.

Also: some people merge all the bam-files for each sample together and mark the different lane-runs with the "RG" tag. You can then generate QC for each individual sample-lane replicates by running multiple QoRTs QC runs with the "--readGroup" parameter, with each tag ID directed at a different output directory. In this case, a simple listing of the filename would be insufficient, since multiple replicates would be derived from the same original BAM file.

This is why in the QoRTs companion R-package I recommend the use of a decoder file (although technically all it actually requires is a list of the replicates).

**Comment by royfrancis** [comment]
good points. thanks.
