### ISSUE TITLE
QualityScoreDistribution function

### ISSUE THREAD

**Issue by pzumbo** [hartleys/QoRTs#3]
Hello,

I have some illumina data whose quality scores exceed 41.  Accordingly the QualityScoreDistribution function fails.  Perhaps consider making the QualityScoreDistribution more flexible or capable of handling quality scores above 41.  

Best,
-Paul

**Comment by hartleys** [comment]
Are you sure the Phred scores actually exceed 41, or is it encoded in [Phred+64 format](https://en.wikipedia.org/wiki/FASTQ_format#Encoding)? That format was used by Illumina v1.3 and older. 

Under this encoding, the numeric phred score is encoded using an ascii character starting at the ascii character "@", or decimal code 64. The Phred scores 0 through to 40 are then encoded over the next 40 ascii characters.

If this is the case then you want to convert those scores rather than just increasing the allowed ceiling. Otherwise QoRTs would report Phred scores ranging from 31 to 71, when actually the numeric values are supposed to range from 0 to 40.

I should note that under the current [SAM format specification](https://samtools.github.io/hts-specs/SAMv1.pdf) Phred scores are required to be encoded using the Phred+33 rule.

**Comment by pzumbo** [comment]
Hi.  Yes, this is Phred+33.  I have only seen this two times before (scores as high as 42), and both times the data came from a HiSeq4000.  I contacted Illumina about this, because I wanted to know if the maximum achievable Q-score has increased on the newer platforms.  This is what Illumina had to say,

"We've been seeing some Q41 and Q42 calls in our newer platforms (RTA v2.x).  Having a Q42 call in there isn't out of reasonable expectations.  I don't have access to the RTA tables for the HiSeq 4000 version of RTA, but I do know that on a HiSeq X system the maximum reported Q scores can be 45.   While I do not know if the Q tables between the HiSeq X and HiSeq 4000 versions of RTA are identical, I would say its a safe bet that the maximum reported score is >40.

I know the bcl2fastq2 software guide has a Q table from 0-40, which gives one the impression the maximum score reportable is 40, but RTA is really what generates the Q score and bcl2fastq2 will report whatever corresponding integer value for it.  I admit this is a bit confusing."

So, it seems that the maximum achievable Q-score on newer illumina platforms is as high as 45.  

Best,
-Paul

>>> this is my signature.

**Comment by hartleys** [comment]
Ah. So the data is new, not old, and of course the format has changed again.

I'll add support for this. Once I've run the new build through testing I'll
post a new release. It will be out by Monday at the latest.

**Comment by hartleys** [comment]
The new release (v0.3.17) now supports quality scores in excess of 41.

You will need to add the parameter "--maxPhredScore 45". The quality-score plots will automatically rescale the y-axis to match the highest maxPhredScore in the dataset.

**Comment by hartleys** [comment]
The new release (v0.3.17) now supports quality scores in excess of 41.

You will need to add the parameter "--maxPhredScore 45". The quality-score plots will automatically rescale the y-axis to match the highest maxPhredScore in the dataset.
