### ISSUE TITLE
 QoRTs be installed on that R installation 

### ISSUE THREAD

**Issue by frankbioinfo** [hartleys/QoRTs#39]
Hi, 
This is not really an issue would need some help with setup.

I have two versions of R on my lsf cluster based on the manual which says 
(Note: this requires that R be installed and in the PATH, and that QoRTs be installed on that R installation) for generating plots, I am not sure how to configure QoRTs such that it would generate plots. Currently i do not see any plots under qc plots folder. Could you please help with correct configuration 

bydefault on cluster(which is very old version of R) 
softwares$ which R
/usr/bin/R

updated version of R which is installed in a different path (also QoRT R package is installed here)
softwares$ which R-devel
/gscuser/myname/usr/bin//R-devel

not sure if this is a workaround what i did was 
R-script QC.makeMultiplot.R(this file was already generated)  just executed this using latest version of R (R-script is alias)

**Comment by hartleys** [comment]
So if I understand your problem correctly, you are trying to get QoRTs to generate plots as part of the java QC run, correct?

Just add the version of R that you want to the PATH using the command:

export PATH="/gscuser/myname/usr/bin/R:$PATH"

Then execute the QoRTs QC run.

Note that you'll have to do this each time you open a new shell/command-line/job unless you [add it to your profile and/or rc files](http://www.linfo.org/path_env_var.html).

**Comment by frankbioinfo** [comment]
Thank you for quick response.

**Comment by hartleys** [comment]
This looks fine (assuming your data is indeed stranded using the fr_firststrand rule).

Personally, I usually drop multi-mapped reads, but I have heard good arguments for either way. If you do decide to drop them, then you might need to adjust the minMAPQ parameter depending on which aligner you use (since each aligner uses its own code for indicating "multi-mapped"). It uses the STAR code (255) by default.
