### ISSUE TITLE
Mixture of single-end and paired-end reads error

### ISSUE THREAD

**Issue by Tomoya89** [hartleys/QoRTs#40]
Hi, thank you for the very useful tools in RNA-seq analysis.

I have  several error message when I try to use QoRTs.
I have a paired-end sequence data and I already aligned and sorted it by TopHat and samtools.
Next I tried to make a qortsQCdata, but it seems bam file contain single-end and paired-end reads.
I can't figure out the problem and I hope you could help me with this. 
I attached the log file bellow.

Best regards,
Tomoya
[error_message.pdf](https://github.com/hartleys/QoRTs/files/1184553/error_message.pdf)

**Comment by Tomoya89** [comment]
I passed the problem, single-end and paired-end reads error.
Still I'm trying to solve the another problem.

**Comment by hartleys** [comment]
First off, it looks like you are using a GFF instead of a GTF. You're going
to have to convert it to a GTF.

For using TopHat2 alignments I recommend using the Minmapq 50 parameter as
recommended in the error log. Also, try dropping the keepMultiMapped
parameter, since it can cause issues depending on how that particular
version of the aligner handles multimapped reads.

I can't do much direct testing this week since I'm on vacation and don't
have access to a computer.


On Jul 31, 2017 6:32 AM, "Tomoya89" <notifications@github.com> wrote:

I passed the problem, single-end and paired-end reads error.
Still I'm trying to solve the another problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hartleys/QoRTs/issues/40#issuecomment-319030544>, or mute
the thread

**Comment by Tomoya89** [comment]
Thank you so much for your reply.
I tried to convert GFF  to GFT by using gffread command and do it QoRTs analysis again.
However, I still have the error message, "FATAL ERROR: OutputGtfLine checkFmt: Attribute: "Parent=gene026678" is misformatted! Does not contain the break value: "\s+" pairString.split.length=1. 
Maybe conversion is not going well. I continued to find out the problem.

**Comment by hartleys** [comment]
I dont know that tool, but from the error message I can see the gtf file is
not a proper gtf formatted file.

It has to follow the GTF file format spec, see:
https://genome.ucsc.edu/FAQ/FAQformat#format4

What gffread command?

-steve

On Aug 2, 2017 6:14 AM, "Tomoya89" <notifications@github.com> wrote:

Thank you so much for your reply.
I tried to convert GFF to GFT by using gffread command and do it QoRTs
analysis again.
However, I still have the error message, "FATAL ERROR: OutputGtfLine
checkFmt: Attribute: "Parent=gene026678" is misformatted! Does not contain
the break value: "\s+" pairString.split.length=1.
Maybe conversion is not going well. I continued to find out the problem.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/hartleys/QoRTs/issues/40#issuecomment-319630763>, or mute
the thread

**Comment by Tomoya89** [comment]
I'm not familiar with gffread command, but it seems like cufflinks program.
I checked the format of my gtf file and confirmed the format spec is not correct.
Is there anyway to convert gff file to gtf file?

**Comment by hartleys** [comment]
The problem with the GFF specification is that it's not specific enough. As
a result, every GFF is organized differently and so it's not really
possible to make a tool that will convert any GFF into a valid GTF.

If you or someone you work with is familiar with perl or python you could
write up a converter that way, but it'll probably have to be a custom job
built specifically for your GFF.

**Comment by Tomoya89** [comment]
Thank you so much for your comments.
I got that it will be a custom job for making GTF from GFF file.
And I think it's much faster to find a GTF file in another database site.
