### ISSUE TITLE
numthreads option

### ISSUE THREAD

**Issue by sahilseth** [hartleys/QoRTs#6]
Hi Steve, 
Was wondering is there was a reason why numthreads was marked depreciated?

Thanks

**Comment by hartleys** [comment]
In all of my benchmarks it provided no appreciable speed improvement, and sometimes actually slowed things down. I never got around to hunting down the bottleneck.

Multithreading comes with a whole host of potential problems, cross-platform inconsistencies, etc. I figured that if it provides no benefit it's probably not worth the trouble. At some point I'll probably try splitting up the work in a different way and see if I get improvement.

In the meantime, if you want to improve runtime, you could hypothetically run a few parallel instances of QoRTs QC with different functions assigned using the "--runFunctions" option.

**Comment by sahilseth** [comment]
Thanks for the info. Are all runFunctions independent? I reckon some of them need to be run in a sequence?

**Comment by hartleys** [comment]
So QoRTs was written as a bunch of discrete modules. Most of these modules are responsible for a bunch of different "runFunctions". For example, one module does the gene counts, CDS counts, gene-body calculations, and a bunch of related stuff.

Some of the "runFunctions" have underlying dependencies which will be automatically added if needed. If you run in debug mode it will tell you when it does this.

Generally when I split stuff up I just break off the NVC calculations, because for some reason I haven't been able to optimize that one very well.

Hmm. The next version of QoRTs will list the internal dependencies in the documentation.

**Comment by hartleys** [comment]
I just posted a new release. The documentation now lists the internal dependencies, and from this information you can see which functions can be run separately. 

Also: the QoRTs QC function now generates a log file that includes a random 12-character string. This way multiple QoRTs runs outputting to the same directory won't overwrite each others' log files.

**Comment by sahilseth** [comment]
Awesome!

I might be helpful to have a —noGzipInput in mergeCalls functions (to work well with —noGzipOutput option of QC).

Thanks!

**Comment by hartleys** [comment]
The newest release adds support for gzip-free analysis pipelines.

The --noGzip option for the mergeCounts and mergeAllCounts takes non-gzipped inputs and spits out non-gzipped outputs.

The R package also now checks for non-gzipped versions of each input file.
